### ISSUE TITLE
ToDo's for Launch

### ISSUE THREAD

**Issue by owieth** [owieth/nftime-contracts#4]
11th August:
- [x] Unified Email
- [x] Move Repositiories to Github org
- [x] Vercel Account with Email
- [x] Alchemy Account with Email
- [x] Setup Goerli Alchemy Project
- [x] Setup Mainnet Alchemy Project
- [x] WalletConnect Cloud Account with Email
- [x] Multisig
- [x] NATSPEC on every function
- [x] NATSPEC on every contract (header)
- [x] Good Test Coverage ~80%
- [x] Clock SVG -> Hour hand move based on minute progress
- [x] Redirect clock face to nftype
- [x] integrate mint sound
- [x] update colon on nft
- [x] remove show in gallery button
- [x] Frontend: Goerli & Mainnet setup to work seamlessly
- [x] Frontend: Check Mobile version
- [x] SC: Rework check if nft is already minted (with timestamp instead of date string)
- [x] Update WHAT YOU'LL GET text

28th July:
- [x] ~~Unified Email~~
- [x] ~~Move Repositiories to Github org~~
- [x] ~~Vercel Account with Email~~
- [x] ~~Pinata Account with Email~~
- [x] ~~Alchemy Account with Email~~
- [x] ~~WalletConnect Cloud Account with Email~~
- [x] ~~Multisig~~
